# Generated by Django 5.1.5 on 2025-02-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recherche',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
