# Generated by Django 5.1.5 on 2025-02-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_recherche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recherche',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
