# Generated by Django 5.1.5 on 2025-02-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_recherche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recherche',
        ),
    ]
